<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <script type="application/x-moraso" src="HTML.Meta.PageTitle">
            suffix = " | estima"
        </script>

        <!-- BaseHref :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.BaseHref"></script>
        <!-- BaseHref :: End -->

        <!-- CanonicalTag :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.CanonicalTag"></script>
        <!-- CanonicalTag :: End -->

        <!-- Meta Tags :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.Tags"></script>
        <!-- Meta Tags :: End -->

        <!-- Meta Geo Tags :: Start -->
        <meta name="geo.region" content="DE-NI" />
        <meta name="geo.placename" content="Hoya" />
        <meta name="geo.position" content="52.80912;9.14234" />
        <meta name="ICBM" content="52.80912, 9.14234" />
        <!-- Meta Geo Tags :: End -->

        <!-- Windows 8 Tile :: Start -->
        <meta name="application-name" content="moraso CMS" /> 
        <!--<meta name="msapplication-TileImage" content="<?php echo Aitsu_Config::get('sys.webpath'); ?>skin/gfx/tileImage.png" />-->
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <!-- Windows 8 Tile :: End -->

        <!-- CSS :: Start -->
        <link rel="stylesheet" type="text/css" media="all" href="/skin/css/style.css" />
        <!-- CSS :: End -->

        <!-- JS :: Start -->
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script type="text/javascript" src="/skin/js/clock2.js"></script>
        <script type="text/javascript" src="/skin/js/jQueryRotate.2.2.js"></script>
        <!-- JS :: End -->

        <!-- IE Fix for HTML5 Tags -->
        <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        
        <!-- Analytics -->
    
    </head>
   
   
    <body>
    	<header>
    	<div id="header"> 
    	<nav>
        <!-- Header :: Start -->
        <script type="application/x-moraso" src="Template:Header">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/header/start.phtml 
            
        </script>
    	</nav>
    	</div>
    	</header>
        <!-- Header :: End -->
        
        <!-- Content :: Start -->
        <script type="application/x-moraso" src="Template:Content">
            defaultTemplate = default

            template.default.name = Start
            template.default.file = templates/content/start.phtml 
            
        </script>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <script type="application/x-moraso" src="Template:Footer">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/footer/default.phtml 
        </script>
        <!-- Footer :: End -->

        <!-- JS :: Start -->
        <script type="text/javascript">var $j=jQuery.noConflict();</script>

        <script type="text/javascript">var templateUrl = "http://local.estima.ch/skin/"</script>
        <script type="text/javascript" src="/skin/js/imagesloaded.js"></script>
        <script type="text/javascript" src="/skin/js/smoothscroll.js"></script>
        <script type="text/javascript" src="/skin/js/stickem.js"></script>
        <script type="text/javascript" src="/skin/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/skin/js/responsiveslides.min.js"></script>
        <script type="text/javascript" src="/skin/js/foundation.js"></script>
        <!-- JS :: End -->
        
    </body>
</html>
