<!-- default -->
<script type="application/x-moraso" src="Navigation:main">
	template = main
</script>
<script type="application/x-moraso" src="Navigation:main">
	template = phone
</script>

<div class="feature background-wide">
<div class="gallery-detail">
	<div class="slide-feature">
		<div class="rslides_container" style="min-height: 450px;">
			<script type="application/x-moraso" src="Image:Teaser">
				template = Featured
				width = config
				height = config
				render = config
			</script>
        </div><!--Slide:Container-->
	</div><!--Slide:Feature-->
</div>	
</div><!--Feature-->	