<!-- default -->
<script type="application/x-moraso" src="Navigation:main">
	template = main
</script>
<script type="application/x-moraso" src="Navigation:main">
	template = phone
</script>

<div class="feature background-wide" style="height: 550px;">
	<div>	<!-- start: Map -->
	<!-- starts: Google Maps -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<div id="googlemaps-container-top"></div>
		<div id="googlemaps" class="google-map google-map-full"></div>
		<div id="googlemaps-container-bottom"></div>
		<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
		<script src="/skin/js/jquery.gmap.min.js"></script>
		<script type="text/javascript">
			$('#googlemaps').gMap({
				maptype: 'ROADMAP',
				scrollwheel: true,
				zoom: 15,
				markers: [
				{
					address: 'Allerheiligenstrasse 30, 2540 Grenchen, Switzerland', // Your Adress Here
					html: 'ESTIMA AG',
					popup: false
				}
				],
			});
		</script>	<!-- end: Google Maps -->
	</div>	<!-- end: Map -->	
</div><!--Feature-->	