<!--default2-->
<div class="main">
<div class="content" id="Our-Company">
	<div class="row">
		<div class="grid_12">
			<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h1
            </script>
		</div>
		<!--6-->
		<div class="grid_6 column">
			<script type="application/x-moraso" src="Content.Text:col1head"> tag = h3 </script>
			<script type="application/x-moraso" src="HTML.Content:col1Content"></script>		
		</div>
		<!--12-->
		<div class="grid_6 column">
			<script type="application/x-moraso" src="Content.Text:col2head"> tag = h3 </script>
			<script type="application/x-moraso" src="HTML.Content:col2Content"></script>		
		</div>
		<!--12-->
	</div><!--Row-->
</div><!--Content-->
<div class="promo background-color" style="background:#fff">
	<div class="row center">
		<div class="grid_12">
		
		<h1>Wir setzen Zeichen der Zeit.</h1>
		<!-- <a href="design" class="button border icon">xyz</a> -->
	</div><!--Grid 12-->
	</div><!--Row-->
</div>	
</div><!--Main-->