<!--Produkte-->
<div class="main">
<div class="content" id="Our-Company">
	<div class="row">
		<div class="grid_12">
			<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h1
            </script>
		</div>
	</div><!--Row-->
	<div class="row">
	<script type="application/x-moraso" src="List.Articles:Produkte">
    	categories = 82
    	useOfStartArticle = 2<div></div>
    	template = block1
    	populateWith.col1Content.index = col1Content
    	populateWith.col1head.index = col1head
    	populateWith.col2Content.index = col2Content
    	populateWith.col2head.index = col2head
    </script>
	</div><!--Row-->
</div><!--Content-->
<div class="promo background-color" style="background:#fff">
	<div class="row center">
		<div class="grid_12">
		
		<h1>Wir setzen Zeichen der Zeit.</h1>
		<!-- <a href="design" class="button border icon">xyz</a> -->
	</div><!--Grid 12-->
	</div><!--Row-->
</div>	
</div><!--Main-->