<!--Main-->
<div class="main">
<div class="content " id="Our-Company">
	<div class="row">
		<div class="grid_12">
			<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h2
            </script>
		</div>
		<!--4-->
		<div class="grid_4 column">
			<h3><script type="application/x-moraso" src="HTML.Content:col1head"></script></h3>
			<p>
			<script type="application/x-moraso" src="HTML.Content:col1Content"></script>		
			</p>
		</div>
		<!--8-->
		<div class="grid_4 column">
			<h3><script type="application/x-moraso" src="HTML.Content:col2head"></script></h3>
			<p>
			<script type="application/x-moraso" src="HTML.Content:col2Content"></script>		
			</p>
		</div>
		<!--12-->
		<div class="grid_4 column">
			<h3><script type="application/x-moraso" src="HTML.Content:col3head"></script></h3>
			<p>
			<script type="application/x-moraso" src="HTML.Content:col3Content"></script>		
			</p>
		</div>
	</div><!--Row-->
</div><!--Content-->
<div class="promo background-color" style="background:#fff">
	<div class="row center">
		<div class="grid_12">
		
		<h1>Wir setzen Zeichen der Zeit.</h1>
		<!-- <a href="design" class="button border icon">xyz</a> -->
	</div><!--Grid 12-->
	</div><!--Row-->
</div>	
</div><!--Main-->