<footer>
<div id="footer">
	<div class="more">
		<div class="row">
			<div class="grid_2">
				<a href="/" class="logo">ESTIMA</a>
			</div>
			<div class="grid_10 right hide-phone">
				<script type="application/x-moraso" src="Navigation:meta">
					template = meta
				</script>
			</div>
		</div><!-- Row -->
	</div><!-- More-->

	<div class="info">
		<div class="row">
			<div class="grid_6">
				<div class="love">...</div>
			</div>
			<div class="grid_6 right">
				<div class="copyright">&#0169; 2013. Estima. All Rights Reserved.</div>
			</div>
		</div><!-- Row -->
	</div><!-- Info-->
</div>
</footer>

